sudo: enable
install:
- sudo apt-get install docker
- docker pull zethra/tigeros-build
script:
- docker run -v `pwd`:/build zethra/tigeros-build
deploy:
  provider: release
  api_key:
    secure: "z0Zt9G75Hu2DfPbMuFtvEypLThc2WPMGHwF5iPKRGaUcG4Gwl/zs26dtQJNr7o5e7IPfunjBotH36DHgZwNTZWhOVc9kZbObHaC6mTrUZ7XWitZOcFwg3IOuRPVo3Oox3DB3IxgAZaspK0vo3e4gJmjaCkMcb8mERayDamVMB1/9CcrE+2YRMoWLf8tKYxWAX/YUlBKENYcMOBg1xdiMQgb1NedYFt0i0D1X6gAPGmEQwkFCJ139qysT4rKy9QdS8L0zQK++HRgcgGIcu+WS/QIL6M7PlKhbXlIPTXRI9bLF5hhC2oCrwohMETwxGZporFl9RAi5mZ+IlrifECAZ4kklaws56+iJgFKkleK29KkDN6lDr2H4wkZGM714CmC/0+nHsoWCLpagarCnt3XDivqxaqqZlnE9JO6ylgsfaYJoKxohFlJl7khQhUzvwHHOunSvALv3p6rbagsEyJAShcckQwYuFkH0gUw1FFdbW0fWeJbFjbKTPEMOgYfBXladwxdt47ujX85LVU1pdeTz8PBwW0d/6IxDjenIN+rfCFXOQNB8TIJUsbiTnh8rqyMCCoWxCmXMCGrvrfFEZqWp05s8b72eqYDxRy4yxQKJHzEMInF+yVgAnj9C60SzyGtOAf1anEPGIKd6lJEJfkv6Y3gaksYaCWSJOzSnYsGW6r4="
  file: noarch/tigeros-backgrounds-1.0-16.fc27.noarch.rpm
  skip_cleanup: true
  on:
    tags: true
